# Generated by Django 4.1.1 on 2022-09-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=256)),
                ('codigo_setor', models.IntegerField(max_length=2)),
            ],
        ),
    ]
