# Generated by Django 4.1.1 on 2022-10-25 17:56

from django.db import migrations, models
import verificacao.validator


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='codigo_setor',
            field=models.IntegerField(error_messages={'unique': 'ID já cadastrado, insira outro.'}, unique=True, validators=[verificacao.validator.validate_codigoSetor]),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome_setor',
            field=models.CharField(max_length=256, validators=[verificacao.validator.validate_no_digits]),
        ),
    ]
