# Generated by Django 4.1.1 on 2022-11-17 12:55

from django.db import migrations, models
import verificacao.validator


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0002_alter_setor_codigo_setor_alter_setor_nome_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='codigo_setor',
            field=models.IntegerField(error_messages={'unique': 'ID já cadastrado, insira outro.'}, unique=True, validators=[verificacao.validator.validate_codigoSetor, verificacao.validator.validate_digits]),
        ),
    ]
