# Generated by Django 4.1.1 on 2023-01-03 19:52

from django.db import migrations, models
import verificacao.validator


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0003_alter_setor_codigo_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='id',
        ),
        migrations.AlterField(
            model_name='setor',
            name='codigo_setor',
            field=models.IntegerField(error_messages={'unique': 'ID já cadastrado, insira outro.'}, primary_key=True, serialize=False, unique=True, validators=[verificacao.validator.validate_codigoSetor, verificacao.validator.validate_digits]),
        ),
    ]
