# Generated by Django 4.1.1 on 2023-01-18 19:23

from django.db import migrations, models
import verificacao.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('Nome', models.CharField(max_length=256, validators=[verificacao.validator.validate_no_digits])),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=3)),
                ('Data_Nascimento', models.DateField(validators=[verificacao.validator.validate_data])),
                ('Municipio_Paciente', models.CharField(max_length=256, validators=[verificacao.validator.validate_no_digits])),
                ('cep_paciente', models.CharField(max_length=8, validators=[verificacao.validator.validate_cep, verificacao.validator.validate_digits])),
                ('endereco_paciente', models.CharField(max_length=256, validators=[verificacao.validator.validate_no_digits])),
                ('bairro_paciente', models.CharField(max_length=256, validators=[verificacao.validator.validate_no_digits])),
                ('numero_paciente', models.IntegerField()),
                ('estado_paciente', models.CharField(max_length=2, validators=[verificacao.validator.validate_sigla, verificacao.validator.validate_no_digits])),
                ('Cartao_SUS', models.CharField(error_messages={'unique': 'Cartão do SUS já cadastrado, insira outro'}, max_length=15, unique=True, validators=[verificacao.validator.validate_digits, verificacao.validator.validate_sus])),
                ('cpf_paciente', models.CharField(error_messages={'unique': 'Número de CPF já cadastrado, insira outro.'}, max_length=11, primary_key=True, serialize=False, unique=True, validators=[verificacao.validator.validate_cpf, verificacao.validator.validate_digits])),
                ('Contato_Emergencia', models.CharField(max_length=11, validators=[verificacao.validator.validate_digits, verificacao.validator.validate_contato])),
            ],
        ),
    ]
