# Generated by Django 4.1.1 on 2022-12-05 13:22

from django.db import migrations, models
import verificacao.validator


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_bairro_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cartao_sus_paciente',
            field=models.CharField(error_messages={'unique': 'Cartão do SUS já cadastrado, insira outro'}, max_length=15, primary_key=True, serialize=False, unique=True, validators=[verificacao.validator.validate_digits, verificacao.validator.validate_sus]),
        ),
    ]
