# Generated by Django 4.1.1 on 2023-01-17 19:37

from django.db import migrations, models
import django.db.models.deletion
import verificacao.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor', '0004_remove_setor_id_alter_setor_codigo_setor'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Prontuario', models.CharField(error_messages={'unique': 'Número de Prontuário já cadastrado, insira outro'}, max_length=5, unique=True, validators=[verificacao.validator.validate_numerodocumento, verificacao.validator.validate_digits])),
                ('Medico_Responsavel', models.CharField(max_length=256, validators=[verificacao.validator.validate_no_digits])),
                ('Data_Admissao', models.DateTimeField(validators=[verificacao.validator.validate_data])),
                ('Hora_Admissao', models.TimeField(validators=[verificacao.validator.validate_hora])),
                ('Localizacao_Fisica', models.CharField(max_length=9, validators=[verificacao.validator.validate_localizacao])),
                ('Codigo_Setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setor.setor')),
                ('Numero_CPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
