# Generated by Django 4.1.1 on 2023-01-03 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor', '0004_remove_setor_id_alter_setor_codigo_setor'),
        ('paciente', '0003_remove_paciente_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Prontuario', models.CharField(error_messages={'unique': 'Número de Prontuário já cadastrado, insira outro'}, max_length=5, unique=True)),
                ('Medico_Responsavel', models.CharField(max_length=256)),
                ('Data_Admissao', models.DateTimeField()),
                ('Hora_Admissao', models.TimeField()),
                ('Localizacao_Fisica', models.CharField(max_length=9)),
                ('Codigo_Setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setor.setor')),
                ('Numero_SUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
