# Generated by Django 4.1.1 on 2022-12-05 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0003_remove_paciente_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichamedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Ficha', models.CharField(error_messages={'unique': 'Número de Ficha já cadastrado, insira outro'}, max_length=5, unique=True)),
                ('Data_Hora_Admissao', models.DateTimeField()),
                ('Localizacao_Fisica', models.CharField(error_messages={'unique': 'Localização já cadastrada, insira outra'}, max_length=10, unique=True)),
                ('Numero_SUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
