# Generated by Django 4.1.1 on 2023-01-18 19:23

from django.db import migrations, models
import django.db.models.deletion
import verificacao.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichamedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Ficha', models.CharField(error_messages={'unique': 'Número de Ficha já cadastrado, insira outro'}, max_length=5, unique=True, validators=[verificacao.validator.validate_digits, verificacao.validator.validate_numerodocumento])),
                ('Data_Admissao', models.DateTimeField(validators=[verificacao.validator.validate_data])),
                ('Hora_Admissao', models.TimeField(validators=[verificacao.validator.validate_hora])),
                ('Municipio', models.CharField(max_length=30)),
                ('Localizacao_Fisica', models.CharField(max_length=9, validators=[verificacao.validator.validate_localizacao])),
                ('Numero_CPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CPF', to='paciente.paciente')),
            ],
        ),
    ]
