# Generated by Django 4.1.1 on 2023-01-09 20:10

from django.db import migrations, models
import django.db.models.deletion
import verificacao.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0003_remove_paciente_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichamedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Ficha', models.CharField(error_messages={'unique': 'Número de Ficha já cadastrado, insira outro'}, max_length=5, unique=True, validators=[verificacao.validator.validate_digits, verificacao.validator.validate_numerodocumento])),
                ('Data_Admissao', models.DateTimeField(validators=[verificacao.validator.validate_data])),
                ('Hora_Admissao', models.TimeField(validators=[verificacao.validator.validate_hora])),
                ('Localizacao_Fisica', models.CharField(max_length=9, validators=[verificacao.validator.validate_localizacao])),
                ('Numero_SUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
