# Generated by Django 4.1.1 on 2022-12-15 11:26

from django.db import migrations, models
import verificacao.validator


class Migration(migrations.Migration):

    dependencies = [
        ('fichamedica', '0002_alter_fichamedica_data_admissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamedica',
            name='Hora_Admissao',
            field=models.TimeField(validators=[verificacao.validator.validate_data]),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='Localizacao_Fisica',
            field=models.CharField(max_length=8, validators=[verificacao.validator.validate_localizacao]),
        ),
    ]
