# Generated by Django 4.1.1 on 2022-12-15 11:43

from django.db import migrations, models
import verificacao.validator


class Migration(migrations.Migration):

    dependencies = [
        ('fichamedica', '0003_alter_fichamedica_hora_admissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamedica',
            name='Localizacao_Fisica',
            field=models.CharField(max_length=9, validators=[verificacao.validator.validate_localizacao]),
        ),
    ]
