# Generated by Django 4.1.1 on 2023-01-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichamedica', '0004_alter_fichamedica_localizacao_fisica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamedica',
            name='Hora_Admissao',
            field=models.TimeField(),
        ),
    ]
