# Generated by Django 4.1.1 on 2022-11-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Funcionario', models.CharField(max_length=256)),
                ('CPF_Funcionario', models.CharField(max_length=11)),
                ('Data_Nascimento_Funcionario', models.DateField()),
                ('Contato_Funcionario', models.CharField(max_length=11)),
                ('Endereco_Funcionario', models.CharField(max_length=256)),
                ('Bairro_Funcionario', models.CharField(max_length=256)),
                ('Numero_Funcionario', models.CharField(max_length=256)),
                ('Complemento_Funcionario', models.CharField(max_length=256)),
            ],
        ),
    ]
