# Generated by Django 4.1.1 on 2022-12-05 13:22

from django.db import migrations, models
import verificacao.validator


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='Bairro_Funcionario',
            field=models.CharField(max_length=256, validators=[verificacao.validator.validate_no_digits]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='CPF_Funcionario',
            field=models.CharField(error_messages={'unique': 'CPF já cadastrado, insira outro'}, max_length=11, unique=True, validators=[verificacao.validator.validate_digits, verificacao.validator.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='Contato_Funcionario',
            field=models.CharField(max_length=11, validators=[verificacao.validator.validate_digits, verificacao.validator.validate_contato]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='Data_Nascimento_Funcionario',
            field=models.DateField(validators=[verificacao.validator.validate_data]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='Endereco_Funcionario',
            field=models.CharField(max_length=256, validators=[verificacao.validator.validate_no_digits]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='Nome_Funcionario',
            field=models.CharField(max_length=256, validators=[verificacao.validator.validate_no_digits]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='Numero_Funcionario',
            field=models.CharField(max_length=256, validators=[verificacao.validator.validate_digits]),
        ),
    ]
