# Generated by Django 4.1.1 on 2022-09-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_unidade', models.CharField(help_text='Nome da Unidade: ', max_length=256)),
                ('cnes', models.CharField(help_text='CNES (apenas números): ', max_length=7)),
                ('cnpj', models.CharField(help_text='CNPJ (apenas números): ', max_length=14)),
                ('orgaoEmissor_unidade', models.CharField(help_text='Órgão Emissor: ', max_length=256)),
                ('endereco_unidade', models.CharField(help_text='Endereço: ', max_length=256)),
                ('bairro_unidade', models.CharField(help_text='Bairro: ', max_length=256)),
                ('numero_unidade', models.IntegerField(help_text='Número: ')),
                ('estado_unidade', models.CharField(help_text='Estado: ', max_length=10)),
                ('cep_unidade', models.CharField(help_text='CEP (apenas números): ', max_length=8)),
            ],
        ),
    ]
