# Generated by Django 4.1.1 on 2022-10-25 17:56

from django.db import migrations, models
import verificacao.validator


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0002_alter_unidade_bairro_unidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='cep_unidade',
            field=models.CharField(max_length=8, validators=[verificacao.validator.validate_digits, verificacao.validator.validate_cep]),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='cnes',
            field=models.CharField(error_messages={'unique': 'CNES já cadastrado, insira outro.'}, max_length=7, unique=True, validators=[verificacao.validator.validate_digits, verificacao.validator.validate_cnes]),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='cnpj',
            field=models.CharField(error_messages={'unique': 'CNPJ já cadastrado, insira outro.'}, max_length=14, unique=True, validators=[verificacao.validator.validate_cnpj, verificacao.validator.validate_digits]),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='estado_unidade',
            field=models.CharField(max_length=10, validators=[verificacao.validator.validate_no_digits, verificacao.validator.validate_sigla]),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nome_unidade',
            field=models.CharField(max_length=256, validators=[verificacao.validator.validate_no_digits]),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='orgaoEmissor_unidade',
            field=models.CharField(max_length=256, validators=[verificacao.validator.validate_no_digits]),
        ),
    ]
